theme = "onedark"

[editor]
cursorline = true
gutters = ["diagnostics", "line-numbers"]
line-number = "relative"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 5000 # 5 seocnds

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true

[keys.normal]
C-j = "half_page_down"
C-k = "half_page_up"

[keys.normal.space.D]
b = ":sh gh browse %{buffer_name}:%{cursor_line} -c%sh{latest_pushed_commit}"
